// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_projects_default = defineTool({
  name: "list_projects",
  title: "Lister les projets",
  description: "Liste les projets Euthymia accessibles \xE0 l'utilisateur connect\xE9 (non archiv\xE9s par d\xE9faut).",
  inputSchema: {
    include_archived: z.boolean().optional().describe("Inclure les projets archiv\xE9s")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ include_archived }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("projects").select("id, name, color, is_archived, space_id, sort_order").order("sort_order");
    if (!include_archived) q = q.eq("is_archived", false);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-tasks.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_tasks_default = defineTool2({
  name: "list_tasks",
  title: "Lister les t\xE2ches",
  description: "Liste les t\xE2ches Euthymia visibles par l'utilisateur. Filtres optionnels: statut (todo/in_progress/done), priorit\xE9 (low/medium/high/urgent), list_id, limite (d\xE9faut 50).",
  inputSchema: {
    status: z2.enum(["todo", "in_progress", "done"]).optional(),
    priority: z2.enum(["low", "medium", "high", "urgent"]).optional(),
    list_id: z2.string().optional().describe("Filtrer par liste"),
    limit: z2.number().int().positive().optional().describe("Nombre maximum (d\xE9faut 50, max 200)")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, priority, list_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser2(ctx);
    const max = Math.min(limit ?? 50, 200);
    let q = sb.from("tasks").select("id, title, description, status, priority, due_date, start_date, list_id, tags, progress").order("updated_at", { ascending: false }).limit(max);
    if (status) q = q.eq("status", status);
    if (priority) q = q.eq("priority", priority);
    if (list_id) q = q.eq("list_id", list_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { tasks: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/create-task.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_task_default = defineTool3({
  name: "create_task",
  title: "Cr\xE9er une t\xE2che",
  description: "Cr\xE9e une nouvelle t\xE2che dans une liste Euthymia. list_id est requis (utiliser list_tasks pour d\xE9couvrir des list_id existants).",
  inputSchema: {
    list_id: z3.string().describe("ID de la liste dans laquelle cr\xE9er la t\xE2che"),
    title: z3.string().min(1).describe("Titre de la t\xE2che"),
    description: z3.string().optional(),
    priority: z3.enum(["low", "medium", "high", "urgent"]).optional(),
    status: z3.enum(["todo", "in_progress", "done"]).optional(),
    due_date: z3.string().optional().describe("Date d'\xE9ch\xE9ance ISO 8601"),
    start_date: z3.string().optional().describe("Date de d\xE9but ISO 8601")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser3(ctx);
    const id = crypto.randomUUID();
    const { data, error } = await sb.from("tasks").insert({
      id,
      list_id: input.list_id,
      title: input.title,
      description: input.description ?? "",
      priority: input.priority ?? "medium",
      status: input.status ?? "todo",
      due_date: input.due_date ?? null,
      start_date: input.start_date ?? null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `T\xE2che cr\xE9\xE9e: ${data.id}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/tools/update-task-status.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.99.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var update_task_status_default = defineTool4({
  name: "update_task_status",
  title: "Mettre \xE0 jour le statut d'une t\xE2che",
  description: "Change le statut d'une t\xE2che existante (todo, in_progress, done).",
  inputSchema: {
    task_id: z4.string().describe("ID de la t\xE2che"),
    status: z4.enum(["todo", "in_progress", "done"])
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ task_id, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser4(ctx);
    const { data, error } = await sb.from("tasks").update({ status }).eq("id", task_id).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Statut mis \xE0 jour: ${data.status}` }],
      structuredContent: { task: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jivfyaqpuhutixfjttga";
var mcp_default = defineMcp({
  name: "euthymia-mcp",
  title: "Euthymia ZenFlow",
  version: "0.1.0",
  instructions: "Outils pour Euthymia ZenFlow : gestion de projets et t\xE2ches. Utilise list_projects et list_tasks pour explorer, create_task pour cr\xE9er une t\xE2che dans une liste, et update_task_status pour changer le statut d'une t\xE2che.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_projects_default, list_tasks_default, create_task_default, update_task_status_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
